# Generated by Django 5.2.7 on 2025-11-10 10:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du concurrent')),
                ('base_url', models.URLField(verbose_name='URL du site')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier scraping')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Concurrent',
                'verbose_name_plural': 'Concurrents',
                'db_table': 'competitors',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_identifier', models.CharField(help_text='SKU ou code produit unique', max_length=255, verbose_name='Identifiant produit (SKU)')),
                ('name', models.CharField(max_length=500, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Catégorie')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name="URL de l'image")),
                ('product_url', models.URLField(verbose_name='URL du produit')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix actuel')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('first_detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Première détection')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='competitors.competitor', verbose_name='Concurrent')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('scrape_session_id', models.UUIDField(blank=True, null=True, verbose_name='ID de session de scraping')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='competitors.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Historique de prix',
                'verbose_name_plural': 'Historiques de prix',
                'db_table': 'price_history',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('products_found', models.IntegerField(default=0, verbose_name='Produits trouvés')),
                ('errors', models.JSONField(blank=True, null=True, verbose_name='Erreurs')),
                ('llm_tokens_used', models.IntegerField(default=0, verbose_name='Tokens LLM utilisés')),
                ('raw_html', models.TextField(blank=True, null=True, verbose_name='HTML brut (debug)')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_sessions', to='competitors.competitor', verbose_name='Concurrent')),
            ],
            options={
                'verbose_name': 'Session de scraping',
                'verbose_name_plural': 'Sessions de scraping',
                'db_table': 'scrape_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['user', 'is_active'], name='competitors_user_id_703ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['last_scraped_at'], name='competitors_last_sc_766f85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitor',
            unique_together={('user', 'base_url')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['competitor', 'product_identifier'], name='products_competi_47bf38_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_fce6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['current_price'], name='products_current_948647_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['last_updated_at'], name='products_last_up_d6e938_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('competitor', 'product_identifier')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', 'recorded_at'], name='price_histo_product_976d94_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapesession',
            index=models.Index(fields=['competitor', 'started_at'], name='scrape_sess_competi_f76a30_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapesession',
            index=models.Index(fields=['status'], name='scrape_sess_status_fd67a7_idx'),
        ),
    ]
