# Generated by Django 5.2.7 on 2025-11-10 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('price_increase', 'Augmentation de prix'), ('price_decrease', 'Diminution de prix'), ('new_product', 'Nouveau produit'), ('product_unavailable', 'Produit indisponible'), ('promotion_detected', 'Promotion détectée')], max_length=30, verbose_name="Type d'alerte")),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée')], default='medium', max_length=10, verbose_name='Sévérité')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Ancienne valeur')),
                ('new_value', models.JSONField(verbose_name='Nouvelle valeur')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitors.competitor', verbose_name='Concurrent')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitors.product', verbose_name='Produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='alerts_user_id_578a42_idx'), models.Index(fields=['created_at'], name='alerts_created_965da5_idx'), models.Index(fields=['alert_type'], name='alerts_alert_t_eda531_idx')],
            },
        ),
    ]
